version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: vehicle_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3309:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

  webapp:
    image: tomcat:9.0
    container_name: tomcat-web
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./target/BTL_PTTK.war:/usr/local/tomcat/webapps/BTL_PTTK.war
    depends_on:
      - mysql
    networks:
      - mynetwork

networks:
  mynetwork:
